# Generated by Django 3.2.8 on 2022-02-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmapcontents',
            name='content',
            field=models.CharField(max_length=50, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='roadmapindexes',
            name='index',
            field=models.CharField(max_length=50, verbose_name='詳細'),
        ),
        migrations.AlterField(
            model_name='roadmaptitles',
            name='title',
            field=models.CharField(max_length=30, verbose_name='タイトル'),
        ),
    ]
